<a href="https://colab.research.google.com/github/arnoldkiirya1/Business_Intelligence/blob/main/Machine_learning_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#Import TensorFlow
import tensorflow as tf
print("Tensorflow version: ", tf.__version__)

Tensorflow version:  2.11.0


In [8]:
#Load Dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [9]:
# Build a machine learning model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [10]:
#Predictions
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.4144652 ,  0.1633454 ,  0.18981847,  0.1575932 , -0.09368166,
         0.53737193, -0.42139733,  0.26501954,  0.28930932,  0.03031091]],
      dtype=float32)

In [ ]:
#Deploying Softmax
tf.nn.softmax(predictions).numpy()

array([[0.06979968, 0.07936072, 0.12128997, 0.05623374, 0.11655635,
        0.09050449, 0.19135594, 0.0811682 , 0.07008894, 0.12364198]],
      dtype=float32)

In [14]:
#Loss Function for training
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True)

In [15]:
loss_fn(y_train[:1], predictions).numpy()

1.8754835

In [16]:
# Configure and Compile the model before training the model
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [17]:
#Train and evaluate the model
model.fit(x_train, y_train, epochs=5) # epoch is the number of iteartions

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2980 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1432 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1081 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0889 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0753 - accuracy: 0.9758


In [18]:
# Evaluate your model, check if the model is over fit or good fit or under fit
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0760 - accuracy: 0.9763 - 525ms/epoch - 2ms/step


[0.07601597905158997, 0.9763000011444092]

In [20]:
# Image Classifier
probability_model = tf.keras.Sequential([model,tf.keras.layers.Softmax()])

In [21]:
probability_model(x_train[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.34502018e-08, 6.77809624e-07, 8.78808635e-07, 4.32658270e-02,
        2.44488993e-16, 9.56732213e-01, 1.54743839e-12, 1.13212764e-07,
        6.94832236e-09, 1.93952857e-07],
       [9.99997139e-01, 2.09259259e-12, 2.90023172e-06, 9.87577353e-10,
        4.83738144e-14, 1.72052257e-08, 1.07565938e-08, 3.05923886e-09,
        3.27802603e-08, 2.02514929e-08],
       [3.65899755e-09, 8.05990931e-05, 2.97236955e-04, 2.21960363e-05,
        9.98862267e-01, 3.81153450e-06, 1.89202950e-07, 2.50276906e-04,
        1.50295637e-05, 4.68385726e-04],
       [1.53921320e-08, 9.99943852e-01, 3.92628954e-06, 4.02738323e-08,
        1.07841075e-07, 7.28134486e-09, 7.86522563e-08, 4.58810282e-05,
        6.12421218e-06, 1.79314885e-09],
       [2.57315702e-09, 3.78067142e-08, 7.22112077e-07, 8.65159291e-06,
        4.20765282e-04, 1.98324187e-07, 6.90328003e-11, 4.05614810e-05,
        9.61825499e-05, 9.99432862e-01]], dtype=float32)>