<a href="https://colab.research.google.com/github/arnoldkiirya1/Business_Intelligence/blob/main/Python_modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Working with Numpy (Numerical Python) Scipy (Scientific Python)

#import the numpy module for sinlge use
import numpy

# importing numpy module for multple use
import numpy as np

# Arrays (This is similar to a list just that for it, all elements in it must have the same datatype)
# Arrays make operations with large voulumes of numerical data very fast ( More efficient than lists)

# Create an array from a list ( One Dimension )
a = np.array([1, 4, 5, 6], int) # np.array([#,#,#,#], datatype)
print(a)
print(type(a))
b = np.array([1, 4, 5, 6], float) # np.array([#,#,#,#], datatype)
print(b)
print(type(b))

a[:3] # Accessing the first three items in the array

#Creating Multiple Dimension Array ( More rows and columns)
c = np.array([[1,2,3],[4,5,6]], float) # np.array([[row1], [row1]], datatype)
print(c)

c[1,:] # Skipping the first row and showing row 2

#Array Properties
c.shape # Shape of the Array

c.dtype # Helps us in knowing what type of data is contained in the array

#Array Functions
len(c)

#Statements
# in statatement helps us in checking for values in the array
2 in c



[1 4 5 6]
<class 'numpy.ndarray'>
[1. 4. 5. 6.]
<class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]]


False

In [ ]:
# Reshaping
print(c)
c.shape
d = c.reshape((3,2)) # reshape((#,#))
print(d)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Transpose c
c.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Array Mathematics
a = np.array([1,2,3], int)
b = np.array([5,2,6], int)
#Addition
a + b

array([6, 4, 9])

In [ ]:
#subtraction
a - b

array([-4,  0, -3])

In [ ]:
#Division
a / b

In [ ]:
#multiplication
b * a

array([ 5,  4, 18])

In [ ]:
# Sqaures (Powering)
a**2

array([1, 4, 9])

In [ ]:
# Array Iterations
f = np.array([1,4,5], int)
for x in f:
  print(x)

1
4
5


In [ ]:
g = np.array([[1,2,3], [4,5,6]], int) 
for x in g: # the loop returns a subsection of the array
   print(x)

[1 2 3]
[4 5 6]


In [ ]:
g = np.array([[1,2,3], [4,5,6]], int) 
for (x, y, z) in g: # the loop returns a subsection of the array
  print(x * y * z)

6
120


In [ ]:
#Array Operations ie sum, product, variance, average(mean), sort
h = np.array([2,6,4], int)
h.sum()

12

In [ ]:
h.prod() #product

48

In [ ]:
h.max() # Getting the maximum

6

In [ ]:
h.sort()
h

array([2, 4, 6])

In [ ]:
# Read about Doting Matrices,  Getting inverse of a matrice and Polynomial Mathematics
i = np.poly([8,-5, 6])
print(i)

[  1.  -9. -22. 240.]


In [ ]:
i = np.roots([8,-5, 6])
print(i)

[0.3125+0.807678j 0.3125-0.807678j]
